In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

import numpy as np

#path = "./Data/"
words = []


def train_to_sentence_form(path):
    # reads the file to a format of docs[doc[[sentence1],[sentence2]],...]
    docs=[]
    num_of_sentences = []
    with open(path) as f:
        line = f.readline()
        while line:
            line = line.rstrip('\n').split(" ")
            #print(line)
            num = line.pop(0)
            number = int(num[1:-1])
            num_of_sentences.append(number)
            len_of_sentence = []

            for i,k in enumerate(line):
                if k.startswith('<'):
                    k=k[1:-1]
                    len_of_sentence.append(int(k))
                    line.pop(i)
            doc_sentence=[]       
            sentence=[]
            for j in len_of_sentence:
                sentence = line[:j]
                line=line[j:]
                docs.append( sentence) 
            line = f.readline()
    print(len(docs))
    return docs,num_of_sentences     
    #docs is a list of lists where each list is a different sentence

'''def convert_to_word(the_path):
    data = []
    for line in open(the_path).readlines():
        line = line.rstrip('\n').split()
        L = []
        for i in line:
            try:
                L.append(int(i))
            except:
                continue
        final_L = ''
        for l in L:
            final_L = final_L + ' ' + words[l]
        data.append(final_L[1:])

    return data'''


def multilabel_confusion_matrix(predict,path):
    test_label = [i.strip().split() for i in open(path + "test-label.dat").readlines()]

    for i in range(len(test_label)):
        item = test_label[i]
        for j in range(len(item)):
            item[j] = int(item[j])

        test_label[i] = item

    labels = []

    for item in open(path + "/labels.txt").readlines():
        item = item.replace('\n', '')
        label_name, _ = item.split(', ')
        labels.append(label_name)

    y_true = np.array(test_label)
    y_pred = np.array(predict)

    conf_mat_dict = {}

    for label_col in range(len(labels)):
        y_true_label = y_true[:, label_col]
        y_pred_label = y_pred[:, label_col]
        conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)

    for label, matrix in conf_mat_dict.items():
        print("Confusion matrix for label {}:".format(label))
        print(matrix)
    return



vocabs = open("vocabs.txt").readlines()
for vocab in vocabs:
    word, _ = vocab.split(', ')
    words.append(word)

train_label = [i.strip() for i in open("train-label.dat").readlines()]
train_label = np.array(train_label)

path="train-data.dat"
docs,num_sentences = train_to_sentence_form(path)

#train_data = convert_to_word(path + "/train-data.dat")
data = []
for i in docs:
    final_L = ''
    for l in i:
        final_L = final_L + ' ' + words[int(l)]
    data.append(final_L[1:])
print(data[:12])
print(len(data))       
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(data)
print(X_train_counts.size)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
import pandas as pd
# KMeans clustering a kind of clustering.
from sklearn.cluster import KMeans
print(train_label.size)
number_of_clusters = 20 
km = KMeans(n_clusters=number_of_clusters)
# Normally people fit the matrix
km.fit(X_train_tfidf)
initform = np.zeros([train_label.size,number_of_clusters])







149925
['rubi rail helper demo more info auto complet', 'see new helper action', 'null length substr locat', 'exec messag messag pleas edit remov follow word content', 'roll stone com news song previou next page', 'good vibrat beach boy', 'smell teen spirit nirvana', 'want hold hand beatl', 'hound dog elvi', 'god know beach boy', 'walk line johnni cash', 'heaven led zeppelin']
149925
965852
8251


In [2]:
df = pd.DataFrame(initform,columns=["Cluster "+ str(i) for i in range(20)])
print(km.labels_.size)
clust_labels = km.labels_
acc = 0
for i,val in enumerate(num_sentences):
    for j in range(val):
        df.iloc[i][clust_labels[acc]] += 1
        acc+=1
        
df.head(20)



149925


Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  Cluster 5  \
0         0.0        0.0        1.0        0.0        0.0        1.0   
1         0.0        0.0        0.0       26.0        0.0        1.0   
2         3.0        2.0        1.0       13.0        0.0        0.0   
3         0.0        0.0        0.0        2.0        0.0        0.0   
4         0.0        0.0        2.0        3.0        0.0        0.0   
5         0.0        0.0        0.0        2.0        0.0        0.0   
6         1.0        0.0        0.0       17.0        0.0        0.0   
7         0.0        0.0        0.0        5.0        0.0        0.0   
8         0.0        0.0        1.0        5.0        0.0        0.0   
9         2.0        1.0        2.0       18.0        0.0        0.0   
10        1.0        0.0        2.0       15.0        0.0        2.0   
11        0.0        0.0        0.0        1.0        0.0        1.0   
12        0.0        0.0        0.0        3.0        1.0        0.0   
13        2.0        0.0        1.0       19.0        0.0        0.0   
14        0.0        0.0        2.0       18.0        0.0        4.0   
15        0.0        0.0        0.0        9.0        1.0        2.0   
16        0.0        0.0        0.0        4.0        0.0        0.0   
17        2.0        1.0        1.0       21.0        0.0        0.0   
18        1.0        0.0        0.0       13.0        1.0        0.0   
19        0.0        0.0        0.0        6.0        0.0        0.0   

    Cluster 6  Cluster 7  Cluster 8  Cluster 9  Cluster 10  Cluster 11  \
0         0.0        0.0        0.0        0.0         0.0         0.0   
1         0.0        0.0        0.0        0.0         0.0         1.0   
2         0.0        0.0        0.0        0.0         0.0         0.0   
3         0.0        0.0        0.0        0.0         0.0         0.0   
4         0.0        0.0        0.0        0.0         0.0         0.0   
5         0.0        0.0        0.0        0.0         0.0         0.0   
6         3.0        0.0        0.0        2.0         0.0         0.0   
7         0.0        0.0        0.0        0.0         0.0         0.0   
8         0.0        0.0        0.0        0.0         0.0         0.0   
9         2.0        1.0        0.0        0.0         0.0         0.0   
10        0.0        1.0        0.0        1.0         0.0         0.0   
11        0.0        0.0        0.0        0.0         0.0         0.0   
12        0.0        0.0        1.0        0.0         0.0         0.0   
13        1.0        1.0        0.0        0.0         1.0         0.0   
14        1.0        1.0        0.0        0.0         2.0         0.0   
15        0.0        0.0        0.0        0.0         0.0         1.0   
16        0.0        0.0        0.0        0.0         2.0         0.0   
17        1.0        1.0        0.0        0.0         0.0         0.0   
18        0.0        0.0        0.0        0.0         1.0         1.0   
19        0.0        1.0        0.0        0.0         0.0         0.0   

    Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0          0.0         0.0         0.0         0.0         0.0         0.0   
1          0.0         0.0         0.0         0.0         0.0         0.0   
2          1.0         0.0         1.0         0.0         1.0         7.0   
3          0.0         0.0         0.0         0.0         0.0         0.0   
4          2.0         0.0         0.0         0.0         0.0         0.0   
5          0.0         0.0         0.0         0.0         0.0         1.0   
6          2.0         2.0         0.0         0.0         2.0         1.0   
7          0.0         0.0         0.0         0.0         0.0         0.0   
8          0.0         0.0         0.0         1.0         1.0         0.0   
9          0.0         0.0         0.0         0.0         0.0         0.0   
10         0.0         0.0         0.0         0.0         0.0         2.0   


In [3]:
print("train")
clf = LinearSVC().fit(df, train_label)

test_data,test_sentences = train_to_sentence_form("test-data.dat")
test_label = [i.strip() for i in open("test-label.dat").readlines()]
test_label = np.array(test_label)

data2 = []
for i in test_data:
    final_L = ''
    for l in i:
        final_L = final_L + ' ' + words[int(l)]
    data2.append(final_L[1:])

X_test_counts = count_vect.transform(data2)
X_test_tfidf = tfidf_transformer.transform(X_test_counts)
print("fitting")
km.fit(X_test_tfidf)
print(km.labels_.size)

testform = np.zeros([test_label.size,number_of_clusters])
df_test = pd.DataFrame(testform,columns=["Cluster "+ str(i) for i in range(20)])

clusttest_labels = km.labels_
acctest = 0
for i,val in enumerate(test_sentences):
    for j in range(val):
        df_test.iloc[i][clusttest_labels[acctest]] += 1
        acctest+=1
        
df_test.head(20)

pred = clf.predict(df_test)


train


C:\Users\Peris\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


73363
fitting
73363


FileNotFoundError: [Errno 2] No such file or directory: '/test-label.dat'

In [6]:
def multilabel_confusion_matrix(predict,path):
    test_label = [i.strip().split() for i in open(path + "test-label.dat").readlines()]

    for i in range(len(test_label)):
        item = test_label[i]
        for j in range(len(item)):
            item[j] = int(item[j])

        test_label[i] = item

    labels = []

    for item in open(path + "labels.txt").readlines():
        item = item.replace('\n', '')
        label_name, _ = item.split(', ')
        labels.append(label_name)

    y_true = np.array(test_label)
    y_pred = np.array(predict)

    conf_mat_dict = {}

    for label_col in range(len(labels)):
        y_true_label = y_true[:, label_col]
        y_pred_label = y_pred[:, label_col]
        conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)

    for label, matrix in conf_mat_dict.items():
        print("Confusion matrix for label {}:".format(label))
        print(matrix)
    return
multilabel_confusion_matrix(pred,"")

IndexError: too many indices for array

In [9]:
print(pred)
predict=[]
for p in pred:
    result = p.split()
    for r in range(len(result)):
        result[r] = int(result[r])
    predict.append(result)

multilabel_confusion_matrix(predict,"")

['0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0'
 '0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0'
 '1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0' ...
 '0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0'
 '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0'
 '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0']
Confusion matrix for label programming:
[[2696  310]
 [ 877  100]]
Confusion matrix for label style:
[[3129  626]
 [ 183   45]]
Confusion matrix for label reference:
[[1295 1130]
 [ 940  618]]
Confusion matrix for label java:
[[3440  171]
 [ 353   19]]
Confusion matrix for label web:
[[2711  222]
 [ 971   79]]
Confusion matrix for label internet:
[[3342  104]
 [ 512   25]]
Confusion matrix for label culture:
[[2125 1156]
 [ 478  224]]
Confusion matrix for label design:
[[2222  682]
 [ 788  291]]
Confusion matrix for label education:
[[1776 1404]
 [ 479  324]]
Confusion matrix for label language:
[[3054  446]
 [ 434   49]]
Confusion matrix for label books:
[[2310 1166]
 [ 369  138]]
Confusion matrix for label writing:
[[2829  67