In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

import numpy as np

path = "../Data/"
words = []


def train_to_sentence_form(path):
    # reads the file to a format of docs[doc[[sentence1],[sentence2]],...]
    docs=[]
    num_of_sentences = []
    with open(path) as f:
        line = f.readline()
        while line:
            line = line.rstrip('\n').split(" ")
            #print(line)
            num = line.pop(0)
            #print(num)
            number = int(num[1:-1])
            num_of_sentences.append(number)
            len_of_sentence = []

            for i,k in enumerate(line):
                if k.startswith('<'):
                    k=k[1:-1]
                    len_of_sentence.append(int(k))
                    line.pop(i)
            doc_sentence=[]       
            sentence=[]
            for j in len_of_sentence:
                sentence = line[:j]
                line=line[j:]
                docs.append( sentence) 
            line = f.readline()
    print(len(docs))
    return docs,num_of_sentences     
    #docs is a list of lists where each list is a different sentence





vocabs = open(path+"vocabs.txt").readlines()
for vocab in vocabs:
    word, _ = vocab.split(', ')
    words.append(word)

train_label = [i.strip() for i in open(path+"train-label.dat").readlines()]
train_label = np.array(train_label)

#path="../Data/"
docs,num_sentences = train_to_sentence_form(path+"train-data.dat")

#train_data = convert_to_word(path + "/train-data.dat")
data = []
for i in docs:
    final_L = ''
    for l in i:
        final_L = final_L + ' ' + words[int(l)]
    data.append(final_L[1:])
print(data[:12])
print(len(data))       
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(data)
print(X_train_counts.size)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

149925
['rubi rail helper demo more info auto complet', 'see new helper action', 'null length substr locat', 'exec messag messag pleas edit remov follow word content', 'roll stone com news song previou next page', 'good vibrat beach boy', 'smell teen spirit nirvana', 'want hold hand beatl', 'hound dog elvi', 'god know beach boy', 'walk line johnni cash', 'heaven led zeppelin']
149925
965852


In [2]:
def multilabel_confusion_matrix(predict,path,clustnum=0):
    test_label = [i.strip().split() for i in open(path + "test-label.dat").readlines()]

    for i in range(len(test_label)):
        item = test_label[i]
        for j in range(len(item)):
            item[j] = int(item[j])

        test_label[i] = item

    labels = []

    for item in open(path + "labels.txt").readlines():
        item = item.replace('\n', '')
        label_name, _ = item.split(', ')
        labels.append(label_name)

    y_true = np.array(test_label)
    y_pred = np.array(predict)

    conf_mat_dict = {}

    for label_col in range(len(labels)):
        y_true_label = y_true[:, label_col]
        y_pred_label = y_pred[:, label_col]
        conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)
    f = open("confmatrix"+str(clustnum)+".txt", "w")
    f.close()
    for label, matrix in conf_mat_dict.items():
        print("Confusion matrix for label {}:".format(label))
        f = open("confmatrix"+str(clustnum)+".txt", "a")
        print(matrix)
        f.write("Confusion matrix for label {}:".format(label))
        np.savetxt(f,matrix)
        f.close()
    return

In [3]:
#from pandas import costcla
!pip install costcla
from costcla.metrics import cost_loss
from costcla.models import CostSensitiveLogisticRegression

from sklearn.linear_model import LogisticRegression

def calculate_cost_matrix(y_list):
    y_list_len = len(y_list)
    #print(y_list_len)
    percentage_0 = np.count_nonzero(y_list == 0) / y_list_len
    percentage_1 = np.count_nonzero(y_list == 1) / y_list_len
    #print(percentage_0)
    #print(percentage_1)
    #print(1 / (percentage_0 * y_list_len))
    #print( 1 / (percentage_1 * y_list_len))
    cost_matrix = []
    for i in range(len(y_list)):
        cost_matrix.append([1 / (percentage_0 * y_list_len), 1 / (percentage_1 * y_list_len),  0, 0])

    return np.array(cost_matrix)


C:\Users\Peris\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\Peris\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [4]:
import pandas as pd

test_data,test_sentences = train_to_sentence_form(path+"test-data.dat")
test_label = [i.strip() for i in open(path+"test-label.dat").readlines()]
test_label = np.array(test_label)
train_label = [i.strip() for i in open(path+"train-label.dat").readlines()]
train_label = np.array(train_label)

df = pd.read_csv("../multi-instance/k_means/train_kmeans.csv") 
df_test = pd.read_csv("../multi-instance/k_means/test_kmeans.csv")
#train_label = pd.DataFrame(data = train_label)
labels_models=[]
for i in range (0,20 ):
    tr=[]
    for j in range (0,len(train_label)):
        tr.append(int(train_label[j][2*i]))
    labels_models.append(tr)
    
train_labels = pd.DataFrame(labels_models)
train_labels = train_labels.transpose()
#print(train_labels[:][2])
labels__models=[]
for i in range (0,20 ):
    ts=[]
    for j in range (0,len(test_label)):
        ts.append(int(test_label[j][2*i]))
    labels__models.append(ts)
    
test_labels = pd.DataFrame(labels__models)
test_labels = test_labels.transpose()


73363


In [5]:

#f = CostSensitiveLogisticRegression()
#cost_mat_test = calculate_cost_matrix(test_labels)
pred = pd.DataFrame()
#print(df)
#drop 1st column because of an error in 1st column

#print(df)
from sklearn import preprocessing
x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
x = df_test.values #returns a numpy array
x_scaled = min_max_scaler.transform(x)
df_test = pd.DataFrame(x_scaled)

orderlist = [2,7,4,0,8,6,5,12,10,9,17,11,15,14,3,13,16,1,18,19]
for l in orderlist:
    print(df.shape)
    cost_mat_train = calculate_cost_matrix(train_labels[:][l])
    f = CostSensitiveLogisticRegression()
    f.fit(df, train_labels[:][l],cost_mat_train)
    df['Label'+str(l)] = train_labels[:][l]
    df_test['Label'+str(l)] = f.predict(df_test) 
    pred['Label'+str(l)] = df_test['Label'+str(l)]

predorder = ['Label'+str(i) for i in range(20)]
pred = pred[predorder]
print(pred)
#cost_loss(df_test, pred, cost_mat_test)

(8251, 20)
(8251, 21)
(8251, 22)
(8251, 23)
(8251, 24)
(8251, 25)
(8251, 26)
(8251, 27)
(8251, 28)
(8251, 29)
(8251, 30)
(8251, 31)
(8251, 32)
(8251, 33)
(8251, 34)
(8251, 35)
(8251, 36)
(8251, 37)
(8251, 38)
(8251, 39)
      Label0  Label1  Label2  Label3  Label4  Label5  Label6  Label7  Label8  \
0        1.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
1        0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
2        0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
3        0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
4        0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
3978     0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
3979     0.0     1.0     1.0     1.0     0.0     1.0     1.0     0.0     0.0   
3980     0.0     1.0     1.0     1.0     0.0     1.0     1.0

In [6]:
#print(df_test)
#print(pred)
#print(cost_mat_test.shape)
from sklearn.metrics import accuracy_score
for i in range(20):
    cost_mat_test = calculate_cost_matrix(test_labels[:][i])
    print(cost_loss(test_labels.iloc[:,i], pred.iloc[:,i], cost_mat_test))
    print(accuracy_score(test_labels.iloc[:,i], pred.iloc[:,i]))
'''predict=[]
for p in range(3983):
    #print(p)
    result = []
    for r in range(20):
        x = orderlist.index(r)
        result.append(pred.iloc[p,x])
    predict.append(result)'''
multilabel_confusion_matrix(pred,path)

0.9330680161342277
0.6952046196334422
1.0000000000000002
0.05724328395681647
1.0
0.3911624403715792
1.0
0.09339693698217424
1.0
0.7363796133567663
0.9997098084735925
0.13507406477529502
0.9959383691477566
0.18051719809189054
1.0
0.729098669344715
1.0043136195242681
0.7815716796384635
1.0000000000000004
0.12126537785588752
0.9452339286808614
0.28094401205121766
1.0
0.8799899573186041
1.0026410053691017
0.8684408737132815
0.9594569622808518
0.2093899071051971
0.9734355730596331
0.7165453175997991
1.0
0.8892794376098418
1.1553130624002819
0.7072558373085613
1.0002871912693854
0.8739643484810444
0.9999999999999998
0.9480291237760482
1.0025974025974027
0.9640974140095405
Confusion matrix for label programming:
[[2558  448]
 [ 766  211]]
Confusion matrix for label style:
[[   0 3755]
 [   0  228]]
Confusion matrix for label reference:
[[   0 2425]
 [   0 1558]]
Confusion matrix for label java:
[[   0 3611]
 [   0  372]]
Confusion matrix for label web:
[[2933    0]
 [1050    0]]
Confusion mat