In [ ]:
import numpy as np
import pandas as pd

In [8]:
# load the data use
import pandas as pd
DataTrain = pd.read_csv("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/train_kmeans_svd.csv") 
DataTest = pd.read_csv("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/test_kmeanssvd.csv")

In [9]:
DataTrain.head()

Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  Cluster 5  \
0        0.0        0.0        0.0        0.0        0.0        0.0   
1        0.0        0.0        0.0        0.0        0.0        1.0   
2        0.0        2.0        1.0        0.0        0.0        0.0   
3        0.0        0.0        0.0        0.0        0.0        0.0   
4        0.0        2.0        0.0        0.0        0.0        0.0   

   Cluster 6  Cluster 7  Cluster 8  Cluster 9  Cluster 10  Cluster 11  \
0        0.0        1.0        0.0        0.0         0.0         1.0   
1       25.0        1.0        0.0        0.0         0.0         0.0   
2       15.0        0.0        0.0        6.0         0.0         1.0   
3        2.0        0.0        0.0        0.0         0.0         0.0   
4        1.0        0.0        0.0        0.0         0.0         2.0   

   Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0         0.0         0.0         0.0         0.0         0.0         0.0   
1         0.0         0.0         0.0         0.0         1.0         0.0   
2         3.0         1.0         0.0         0.0         2.0         0.0   
3         0.0         0.0         0.0         0.0         0.0         0.0   
4         0.0         0.0         2.0         0.0         0.0         0.0   

   Cluster 18  Cluster 19  
0         0.0         0.0  
1         0.0         0.0  
2         0.0         0.0  
3         0.0         0.0  
4         0.0         0.0

In [10]:
DataTest.head()

Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  Cluster 5  \
0        0.0        0.0        1.0        0.0        0.0        0.0   
1        1.0        2.0        0.0        0.0        0.0        0.0   
2        0.0        2.0        0.0        0.0        0.0        2.0   
3        0.0        5.0        3.0        0.0        1.0        0.0   
4        0.0        0.0        0.0        1.0        0.0        0.0   

   Cluster 6  Cluster 7  Cluster 8  Cluster 9  Cluster 10  Cluster 11  \
0       14.0        0.0        1.0        7.0         0.0         1.0   
1       18.0        0.0        2.0        0.0         0.0         2.0   
2       21.0        0.0        0.0        1.0         0.0         1.0   
3        4.0        2.0        0.0        1.0         0.0         0.0   
4        1.0        0.0        0.0        2.0         0.0         0.0   

   Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0         3.0         0.0         0.0         1.0         0.0         2.0   
1         2.0         1.0         0.0         3.0         0.0         0.0   
2         1.0         2.0         0.0         0.0         1.0         0.0   
3         0.0         0.0         2.0         1.0         0.0         0.0   
4         0.0         0.0         0.0         0.0         0.0         0.0   

   Cluster 18  Cluster 19  
0         1.0         0.0  
1         0.0         0.0  
2         0.0         0.0  
3         0.0         0.0  
4         0.0         0.0

In [11]:
DataTrain.shape

(8251, 20)

In [12]:
DataTest.shape

(3983, 20)

In [13]:
labels = []

for item in open("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/labels.txt").readlines():
    item = item.replace('\n', '')
    label_name, _ = item.split(', ')
    labels.append(label_name)

In [ ]:
labels

In [14]:
y_train = np.loadtxt("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/train-label.dat")
y_test =  np.loadtxt("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/test-label.dat")

In [15]:
X_train = DataTrain
X_test = DataTest

In [16]:
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("X_test shape: ",X_test.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (8251, 20)
y_train shape:  (8251, 20)
X_test shape:  (3983, 20)
y_test shape:  (3983, 20)


 #  Train 

In [17]:
# using Label Powerset
# train the TFId X_train
import time
from skmultilearn.problem_transform import LabelPowerset
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

classifiers = [RandomForestClassifier(n_estimators=50, criterion='gini'),
               SVC(kernel='rbf', C=1),
              KNeighborsClassifier(n_neighbors=60)]
state=[]
for classifier in classifiers:
    start = time.time()
    clf = LabelPowerset(classifier = classifier, require_dense=[False, True])
    clf.fit(X_train,y_train)
    predictions = clf.predict(X_test)
    print("time: ",  time.time() - start)
    conf_matr = metrics.multilabel_confusion_matrix(y_test, predictions)
    state.append([classifier, conf_matr])

time:  31.520745277404785
time:  284.3582785129547
time:  2.581221342086792


In [18]:
# return the name of the classifier
def print_estimator_name(estimator):
    return estimator.__class__.__name__

In [21]:
def results(state):
    results=[]
    for states in state:
        cl = print_estimator_name(states[0]) #['classifier']
        
        print("\nClassifier: %s " %cl)
        print("Confusion matrices per label \n")
        BA = []
        for i in range(len(labels)):
            print("Label: ", labels[i])
            print(states[-1][i])
            TPR = states[-1][i][1][1]/(states[-1][i][1][1]+states[-1][i][1][0]) # TPR=TP/(TP+FN) #Recall
            TNR = states[-1][i][0][0]/(states[-1][i][0][0]+states[-1][i][0][1]) # TNR = TN/(TN+FP) #specificity
            balanced_accuracy = round((TPR+TNR)/2,3)
#             print("Balanced_accuracy: ", balanced_accuracy)
            BA.append(balanced_accuracy)
            results.append([cl, labels[i], balanced_accuracy])
        print("\nBalanced accuracy per label ")
        for i in range(len(labels)):
            print(str(labels[i]) + " : %s " % (BA[i]))
    return results

In [22]:
# acquire the results 
result = results(state)


Classifier: RandomForestClassifier 
Confusion matrices per label 

Label:  programming
[[2423  583]
 [ 659  318]]
Label:  style
[[3585  170]
 [ 201   27]]
Label:  reference
[[1728  697]
 [1011  547]]
Label:  java
[[3244  367]
 [ 300   72]]
Label:  web
[[2360  573]
 [ 678  372]]
Label:  internet
[[3115  331]
 [ 474   63]]
Label:  culture
[[2878  403]
 [ 591  111]]
Label:  design
[[2242  662]
 [ 779  300]]
Label:  education
[[2768  412]
 [ 640  163]]
Label:  language
[[3230  270]
 [ 426   57]]
Label:  books
[[3154  322]
 [ 457   50]]
Label:  writing
[[3242  263]
 [ 425   53]]
Label:  computer
[[3148  326]
 [ 450   59]]
Label:  english
[[3413  215]
 [ 316   39]]
Label:  politics
[[3304  287]
 [ 332   60]]
Label:  history
[[3290  252]
 [ 388   53]]
Label:  philosophy
[[3558  156]
 [ 231   38]]
Label:  science
[[3163  319]
 [ 436   65]]
Label:  religion
[[3651  125]
 [ 181   26]]
Label:  grammar
[[3788   62]
 [ 124    9]]

Balanced accuracy per label 
programming : 0.566 
style : 0.537 
re