In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from scipy.spatial.distance import directed_hausdorff
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
import numpy as np
import datetime as dt
import pandas as pd

In [4]:
#to load the data use
import pandas as pd
DataTrain = pd.read_csv("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/train_kmedoids__.csv") 
DataTest = pd.read_csv("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/test_kmedoids__.csv")

In [5]:
DataTrain.head(5)

Unnamed: 0  Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  \
0           0   0.414548   0.401836   0.426836   0.411074   0.836155   
1           1   0.372133   0.328745   0.368366   0.374088   0.760516   
2           2   0.419354   0.413711   0.399528   0.423316   0.759667   
3           3   0.233521   0.344603   0.373293   0.185321   0.700270   
4           4   0.388933   0.371395   0.367590   0.433855   0.694607   

   Cluster 5  Cluster 6  Cluster 7  Cluster 8  ...  Cluster 10  Cluster 11  \
0   0.544826   0.407771   0.408575   0.579547  ...    0.579162    0.391801   
1   0.490156   0.372669   0.238157   0.641974  ...    0.533825    0.307718   
2   0.488866   0.330713   0.396701   0.599053  ...    0.532925    0.411040   
3   0.524134   0.376851   0.319734   0.631277  ...    0.548552    0.308023   
4   0.490917   0.403075   0.410760   0.596351  ...    0.544618    0.259998   

   Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0    0.955807    0.412778    0.570592    0.427822    0.433890    0.831481   
1    0.934594    0.364070    0.653746    0.366005    0.371403    0.431278   
2    0.742596    0.424959    0.596838    0.336061    0.325223    0.605831   
3    0.841190    0.307854    0.646235    0.301611    0.388868    0.835004   
4    0.934694    0.416376    0.594559    0.377108    0.410364    0.798560   

   Cluster 18  Cluster 19  
0    0.334216    0.536428  
1    0.362992    0.490171  
2    0.321356    0.496524  
3    0.285463    0.511169  
4    0.413026    0.501732  

[5 rows x 21 columns]

In [6]:
DataTrain = DataTrain.iloc[:,1:]

In [7]:
DataTrain.head()

Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  Cluster 5  \
0   0.414548   0.401836   0.426836   0.411074   0.836155   0.544826   
1   0.372133   0.328745   0.368366   0.374088   0.760516   0.490156   
2   0.419354   0.413711   0.399528   0.423316   0.759667   0.488866   
3   0.233521   0.344603   0.373293   0.185321   0.700270   0.524134   
4   0.388933   0.371395   0.367590   0.433855   0.694607   0.490917   

   Cluster 6  Cluster 7  Cluster 8  Cluster 9  Cluster 10  Cluster 11  \
0   0.407771   0.408575   0.579547   0.944473    0.579162    0.391801   
1   0.372669   0.238157   0.641974   0.850228    0.533825    0.307718   
2   0.330713   0.396701   0.599053   0.858785    0.532925    0.411040   
3   0.376851   0.319734   0.631277   0.814152    0.548552    0.308023   
4   0.403075   0.410760   0.596351   0.799618    0.544618    0.259998   

   Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0    0.955807    0.412778    0.570592    0.427822    0.433890    0.831481   
1    0.934594    0.364070    0.653746    0.366005    0.371403    0.431278   
2    0.742596    0.424959    0.596838    0.336061    0.325223    0.605831   
3    0.841190    0.307854    0.646235    0.301611    0.388868    0.835004   
4    0.934694    0.416376    0.594559    0.377108    0.410364    0.798560   

   Cluster 18  Cluster 19  
0    0.334216    0.536428  
1    0.362992    0.490171  
2    0.321356    0.496524  
3    0.285463    0.511169  
4    0.413026    0.501732

In [8]:
DataTest = DataTest.iloc[:,1:]

In [10]:
DataTest.head()

Cluster 0  Cluster 1  Cluster 2  Cluster 3  Cluster 4  Cluster 5  \
0   0.565573   0.547392   0.495616   0.562451   0.703978   0.502939   
1   0.469409   0.401623   0.333249   0.476613   0.805703   0.342119   
2   0.384557   0.312924   0.389292   0.411835   0.672799   0.466394   
3   0.473452   0.466551   0.401149   0.464564   0.791047   0.513305   
4   0.808575   0.753974   0.706795   0.797602   0.359352   0.732952   

   Cluster 6  Cluster 7  Cluster 8  Cluster 9  Cluster 10  Cluster 11  \
0   0.461356   0.533346   0.511473   0.812625    0.483915    0.535096   
1   0.432360   0.461758   0.433043   0.918064    0.466054    0.445373   
2   0.409785   0.382691   0.577415   0.796995    0.535203    0.368254   
3   0.459288   0.471535   0.606052   0.919412    0.504188    0.454072   
4   0.805603   0.805271   0.680269   0.308018    0.543955    0.719199   

   Cluster 12  Cluster 13  Cluster 14  Cluster 15  Cluster 16  Cluster 17  \
0    0.789981    0.569305    0.555282    0.481415    0.455797    0.754616   
1    0.855148    0.469964    0.451244    0.422415    0.450098    0.795665   
2    0.916947    0.402691    0.560840    0.409079    0.402178    0.741018   
3    0.831151    0.467442    0.616263    0.479776    0.501343    0.800062   
4    0.936394    0.686095    0.807068    0.580584    0.716676    0.803696   

   Cluster 18  Cluster 19  
0    0.469166    0.607302  
1    0.381937    0.575796  
2    0.413112    0.499199  
3    0.447599    0.533876  
4    0.806966    0.847615

In [11]:
DataTrain.shape

(8251, 20)

In [12]:
DataTest.shape

(3983, 20)

In [14]:
labels = []

for item in open("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/labels.txt").readlines():
    item = item.replace('\n', '')
    label_name, _ = item.split(', ')
    labels.append(label_name)

In [15]:
labels

['programming',
 'style',
 'reference',
 'java',
 'web',
 'internet',
 'culture',
 'design',
 'education',
 'language',
 'books',
 'writing',
 'computer',
 'english',
 'politics',
 'history',
 'philosophy',
 'science',
 'religion',
 'grammar']

In [16]:
y_train = np.loadtxt("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/train-label.dat")
y_test =  np.loadtxt("C:/Users/User/Desktop/AI/10. Artificial Intelligence/4. 4rth semester/Advanced ML/project/datasets/DeliciousMIL/Data/test-label.dat")

In [17]:
X_train = DataTrain
X_test = DataTest

In [18]:
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("X_test shape: ",X_test.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (8251, 20)
y_train shape:  (8251, 20)
X_test shape:  (3983, 20)
y_test shape:  (3983, 20)


 #  Train 

In [49]:
# using Label Powerset
# train the TFId X_train
import time
from skmultilearn.problem_transform import LabelPowerset
# from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

classifiers = [RandomForestClassifier(n_estimators=50, criterion='gini'),
               SVC(kernel='rbf', C=1),
              KNeighborsClassifier(n_neighbors=60)]
state=[]
for classifier in classifiers:
    start = time.time()
    clf = LabelPowerset(classifier = classifier, require_dense=[False, True])
    clf.fit(X_train,y_train)
    predictions = clf.predict(X_test)
    print("time: ",  time.time() - start)
    conf_matr = metrics.multilabel_confusion_matrix(y_test, predictions)
    state.append([classifier, conf_matr])

time:  193.81274604797363
time:  346.37834644317627
time:  4.579753637313843


In [ ]:
# return the name of the classifier
def print_estimator_name(estimator):
    return estimator.__class__.__name__

In [80]:
def results(state):
    results=[]
    for states in state:
        cl = print_estimator_name(states[0]) #['classifier']
        
        print("\nClassifier: %s " %cl)
        print("Confusion matrices per label \n")
        BA = []
        for i in range(len(labels)):
            print("Label: ", labels[i])
            print(states[-1][i])
            TPR = states[-1][i][1][1]/(states[-1][i][1][1]+states[-1][i][1][0]) # TPR=TP/(TP+FN) #Recall
            TNR = states[-1][i][0][0]/(states[-1][i][0][0]+states[-1][i][0][1]) # TNR = TN/(TN+FP) #specificity
            balanced_accuracy = round((TPR+TNR)/2,3)
#             print("Balanced_accuracy: ", balanced_accuracy)
            BA.append(balanced_accuracy)
            results.append([cl, labels[i], balanced_accuracy])
        print("\nBalanced accuracy per label ")
        for i in range(len(labels)):
            print(str(labels[i]) + " : %s " % (BA[i]))
    return results, BA

In [81]:
# acquire the results [confusion matrix, accuracy, precisioni, recall, f1]
result = results(state)


Classifier: RandomForestClassifier 
Confusion matrices per label 

Label:  programming
[[2488  518]
 [ 676  301]]
Label:  style
[[3549  206]
 [ 202   26]]
Label:  reference
[[1818  607]
 [1123  435]]
Label:  java
[[3279  332]
 [ 298   74]]
Label:  web
[[2323  610]
 [ 768  282]]
Label:  internet
[[3105  341]
 [ 484   53]]
Label:  culture
[[2974  307]
 [ 602  100]]
Label:  design
[[2314  590]
 [ 817  262]]
Label:  education
[[2878  302]
 [ 683  120]]
Label:  language
[[3299  201]
 [ 425   58]]
Label:  books
[[3293  183]
 [ 461   46]]
Label:  writing
[[3328  177]
 [ 430   48]]
Label:  computer
[[3244  230]
 [ 463   46]]
Label:  english
[[3420  208]
 [ 318   37]]
Label:  politics
[[3360  231]
 [ 338   54]]
Label:  history
[[3387  155]
 [ 407   34]]
Label:  philosophy
[[3610  104]
 [ 258   11]]
Label:  science
[[3284  198]
 [ 448   53]]
Label:  religion
[[3684   92]
 [ 192   15]]
Label:  grammar
[[3811   39]
 [ 123   10]]

Balanced accuracy per label 
programming : 0.568 
style : 0.53 
ref